platform :android do
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore beta'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end
end

platform :ios do
  desc "Fetch certificates and provisioning profiles"
  lane :certificates do
    match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
    match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
  end

  desc "Build the ios  application"
  private_lane :build do
    certificates 
    increment_build_number(xcodeproj: './ios/name.xcodeproj')
    gym(scheme: "name", project: "./ios/name.xcodeproj")
  end

  desc "Shipe to TestFlight."
  lane :beta do
    build
    pilot
    commit_version_bump(message: "Bump build", xcodeproj: './ios/name.xcodeproj')
    push_to_git_remote
  end
end


